export type TeamMember = { name: string; role: string };

// The Peloton. Roles as listed on the live site (includes the office dogs).
export const TEAM: TeamMember[] = [
  { name: "Henry Daglish", role: "CEO & Co-Founder" },
  { name: "Pedro Avery", role: "Chairman & Co-Founder" },
  { name: "Erika Mari", role: "CCO & Co-Founder" },
  { name: "Carol Middleton", role: "Chief Client & Growth Officer" },
  { name: "Mark Pavlika (Pav)", role: "Chief People & Purpose Officer" },
  { name: "Jim Elliott", role: "Commercial Director & Partner" },
  { name: "Reema Patel", role: "Finance Director & Partner" },
  { name: "Simone Gayle", role: "Managing Partner, Digital & Transformation" },
  { name: "Natalie Jackson", role: "Managing Partner, Bicycle Ripple" },
  { name: "Abi Bateman", role: "Paid Social Account Director" },
  { name: "Aidan Mark", role: "Media Science & Strategy Director" },
  { name: "Alastair Jones", role: "International AV Director" },
  { name: "Alex Eyles", role: "Account Director" },
  { name: "Alex Wood", role: "Business Director" },
  { name: "Alina de Villiers-Hill", role: "Senior Account Executive" },
  { name: "Andres Pico", role: "Senior Paid Social Executive" },
  { name: "Becky Gemmell", role: "Senior AV Account Manager" },
  { name: "Becky Gwynne", role: "Paid Search Account Manager" },
  { name: "Bryan Hogg", role: "Senior Strategy Director" },
  { name: "Charlotte Wheatley", role: "Business Director, Bicycle Studio" },
  { name: "Chris Ball", role: "Account Manager" },
  { name: "Christina Smith", role: "Head of Operations" },
  { name: "Connor Dimberline", role: "Designer" },
  { name: "Daisy Graham", role: "Director Domestique" },
  { name: "Daniela Ochoa", role: "Account Executive, Bicycle Studio" },
  { name: "Demi Cumming", role: "Senior Account Executive" },
  { name: "Dylan Edwards", role: "Senior Account Executive" },
  { name: "Dylan Pritchard", role: "Head of AV" },
  { name: "Eleanor Sibley", role: "Media Executive" },
  { name: "Evie Hutcheon", role: "Senior Account Executive" },
  { name: "Fred Scriven", role: "AV Director" },
  { name: "Frediano Iannelli", role: "Strategy & Digital Transformation Director" },
  { name: "George Lilley-Moncrieff", role: "Performance Director" },
  { name: "Georgie Hobley", role: "Business Director" },
  { name: "Hana Chowdhury", role: "Data Analyst" },
  { name: "Hannah Saunders", role: "Business Director" },
  { name: "Harrison Zhang", role: "Media Executive" },
  { name: "Hiten Shah", role: "Financial Controller" },
  { name: "Izzy Nott", role: "Account Manager, Bicycle Studio" },
  { name: "Jae Rich", role: "Paid Social Manager" },
  { name: "Joe Eaton", role: "Senior Management Accountant" },
  { name: "Josh Andrews", role: "Account Director" },
  { name: "Laura Jarvis", role: "Executive Assistant" },
  { name: "Lottie Thomas", role: "Account Director" },
  { name: "Louis Aidam", role: "Senior Research Executive" },
  { name: "Luca Wieynk", role: "Media Executive" },
  { name: "Lucas Miracca", role: "Senior Account Manager" },
  { name: "Matt Sharkey", role: "Head of Activation" },
  { name: "Mavina Bhatta", role: "Senior Account Manager" },
  { name: "Megan Hume", role: "Senior Paid Social Executive" },
  { name: "Ollie Makin", role: "Senior Account Executive" },
  { name: "Ollie Walker", role: "New Business & Marketing Director" },
  { name: "Poppy Pressland", role: "Paid Search Executive" },
  { name: "Quincy Boateng", role: "AV Account Manager" },
  { name: "Richard Cavill", role: "Head of Programmatic" },
  { name: "Rohan Patel", role: "Media Executive" },
  { name: "Sam Atkinson", role: "Finance Assistant" },
  { name: "Sam Staniforth", role: "Account Director" },
  { name: "Sarah Kong", role: "Business Director" },
  { name: "Shivani Patel", role: "Operations Manager" },
  { name: "Teo Borozan", role: "Senior Programmatic Account Manager" },
  { name: "Valeria Perticucci", role: "Peloton Success Manager" },
  { name: "Yash Kaushik", role: "Programmatic Account Manager" },
  { name: "Baxter", role: "Chief Barking Officer" },
  { name: "Luna", role: "Chief Cuddle Officer" },
  { name: "Nelly", role: "Head of Barketing" },
];

export function initials(name: string): string {
  const parts = name.replace(/\(.*?\)/g, "").trim().split(/\s+/);
  const first = parts[0]?.[0] ?? "";
  const last = parts.length > 1 ? parts[parts.length - 1][0] : "";
  return (first + last).toUpperCase();
}
